### ISSUE TITLE
Optional: use PHP RPMs from remirepo

### ISSUE THREAD

**Issue by amuehlem** [amuehlem/MISP-RPM#23]
http://rpms.remirepo.net/enterprise/8/php74/x86_64/repoview/

**Comment by HarryTBB** [comment]
Hi amuehlem,

I am new to MISP as well as Apache. I just tried your installation package and it worked fine with CentOS 7.7. Thanks for your effort!
I just had some issues with MISP integration with LDAP using php72w-ldap module. However, I found it really difficult to install the module because of the version conflict of php.  
`file /var/lib/php from install of php72w-common-7.2.27-1.w7.x86_64 conflicts with file from package php-7.2.27-2.el7.x86_64`
Am I able to replace the php package from your provided repo with the one from dependency check? 

Just thought  this might be related to the topic and left a comment here.

Harry

**Comment by amuehlem** [comment]
Hi Harry

php72w-common seems like a php 7.2 package. The current misp installation should install php 7.4 from the REMI repo instead.

Can you check which php package you have installed?

There is a php74-php-ldap available on the REMI repo, this should not have any conflicts with the other php packages from his repository.

**Comment by amuehlem** [comment]
done with misp 2.4.145
