### ISSUE TITLE
New version of MISP and MariaDB

### ISSUE THREAD

**Issue by romarito90** [amuehlem/MISP-RPM#87]
HI, Andreas 

first, thank you for your hard effort and support to mantain this MISP version of RPMs 

I have 2 questions 

first. I need to change the virtual-env package with the same misp version like this below 

https://certrepo.switch.ch/certrepo/misp8/misp-2.4.177-1.el8.x86_64.rpm
https://certrepo.switch.ch/certrepo/misp8/misp-python-virtualenv-2.4.177-1.el8.x86_64.rpm

This when I need to upgrade to a new version of MISP???

Second question.-  Can I use or change another version of MariaDB without issues with MISP??

I have this question because I saw that the repo has the version 10.8 and install that version. So MariaDB has newest stable versions like 10.9, 10.10, 10.11, 11.0, 11.1

**Comment by amuehlem** [comment]
Hi romarito90

You could create your own virtual-env package and activate it in the MISP configuration (python_path or similar). I just generate with every MISP release a new virtual-env, because usually the misp-stix and pymisp packages get updated with every new version of misp. In your own virtual env you then have to make sure this versions are updated as well.

MariaDB should be more or less in dependent from the MISP, I don't see a problem when upgrading to a newer version.

**Comment by romarito90** [comment]
Hi, Andreas

Thank you so much for your answer 

Regards 

Romarito
